name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: C-C-C0de
          template: classic
          base: activity, repositories  
          config_theme: "merko"
          config_display: compact
          
          repositories: true
          repositories_limit: 3        
          repositories_features: traffic 
          repositories_languages: false  
          repositories_description: false
          
          plugins: followers
          config_timezone: Europe/Moscow
