name: Repositories Stats
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: C-C-C0de
          
          template: classic
          config_theme: "merko"
          config_background_color: "0D1117"
          config_border: true
          config_border_color: "3B9600"
          
          plugins: repositories
          
          plugin_repositories: yes
          plugin_repositories_description: no
          plugin_repositories_languages: no
          plugin_repositories_limit: 0
          plugin_repositories_features: traffic, stars
          plugin_repositories_order: stars
          
          base: ""
          header: no
          activity: no
          community: no
          metadata: no
          
          config_timezone: Europe/Moscow
