name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: C-C-C0de
          template: classic
          base: header, activity, community, repositories, metadata
          config_theme: "merko"
          config_background_color: "0D1117"
          config_border: true
          config_border_color: "3B9600"
          
          repositories: true
          repositories_forks: true               
          repositories_limit: 10
          repositories_features: traffic
          repositories_affiliations: owner, collaborator
          
          plugins: stars, followers
          config_timezone: Europe/Moscow
